<?php
if (!defined('ABSPATH')) exit;

class GreenAudit_PDF_Report {
    
    public function generate($data = []) {
        // Load DomPDF (assumes /lib/dompdf/ with autoload.inc.php)
        $autoload = GREENAUDIT_PATH . 'lib/dompdf/autoload.inc.php';
        if (!file_exists($autoload)) {
            return new WP_Error('dompdf_missing', 'DomPDF not found. Check /lib/dompdf/autoload.inc.php');
        }
        require_once $autoload;
        
        $dompdf = new \Dompdf\Dompdf([
            'defaultFont' => 'Helvetica',
            'isRemoteEnabled' => false,
            'isHtml5ParserEnabled' => true
        ]);
        
        $carbon = isset($data['carbon']) ? $data['carbon'] : 'N/A';
        $energy = isset($data['energy']) ? $data['energy'] : 'N/A';
        $host = parse_url(home_url(), PHP_URL_HOST);
        $date = date('F j, Y');

        // Build optimization list (only if passed in)
        $optimizations_html = '';
        if (!empty($data['optimizations'])) {
            $items = [];
            foreach ($data['optimizations'] as $opt) {
                $items[] = "• {$opt}";
            }
            $optimizations_html = '<p><strong>✅ Optimizations applied:</strong><br>' . implode('<br>', $items) . '</p>';
        }

        $html = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                body { 
                    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; 
                    margin: 2cm; 
                    line-height: 1.6; 
                    color: #333; 
                }
                h1 { 
                    color: #2E7D32; 
                    text-align: center; 
                    margin: 0 0 5px 0; 
                    font-size: 24pt; 
                }
                .subtitle { 
                    text-align: center; 
                    color: #666; 
                    font-size: 10pt; 
                    margin: 0 0 20px 0; 
                    line-height: 1.3; 
                }
                .highlight { 
                    font-weight: bold; 
                    color: #1B5E20; 
                }
                blockquote { 
                    font-style: italic; 
                    color: #212121; 
                    margin: 20px 0; 
                    padding: 15px 20px; 
                    border-left: 3px solid #4CAF50; 
                    background: #f8fff8; 
                    font-size: 10pt; 
                }
                hr { 
                    border: 0; 
                    border-top: 1px solid #eee; 
                    margin: 20px 0; 
                }
                .footer { 
                    margin-top: 30px; 
                    font-size: 9pt; 
                    color: #555; 
                    border-top: 1px solid #eee; 
                    padding-top: 15px; 
                    line-height: 1.5; 
                }
                a { color: #1976D2; text-decoration: none; }
                a:hover { text-decoration: underline; }
            </style>
        </head>
        <body>
            <h1>Green Audit Report</h1>
            <p class="subtitle">
                Generated by GreenAudit WP — an open tool by ECO Web Tools<br>
                Website: <strong>' . esc_html($host) . '</strong><br>
                Date: ' . $date . '
            </p>
            
            <hr>
            
            <blockquote>
                The internet consumes <strong>1021 TWh per year</strong> to be precise. 
                To give you some perspective, that’s <strong>more than the entire United Kingdom</strong>.
                <br><br>
                From data centres to transmission networks to the billions of connected devices that we hold in our hands, 
                it is all consuming electricity, and in turn producing carbon emissions <strong>equal to or greater than the global aviation industry</strong>.
            </blockquote>
            
            <p><strong>This website’s footprint:</strong></p>
            <ul>
                <li><strong>Carbon per visit:</strong> <span class="highlight">' . $carbon . ' g CO2</span></li>
                <li><strong>Energy per visit:</strong> <span class="highlight">' . $energy . ' kWh</span></li>
            </ul>
            
            <p>
                <em>Estimate via the original 
                <a href="https://www.websitecarbon.com/methodology/">Website Carbon Calculator methodology</a> 
                (Wholegrain Digital, 2018)</em>
            </p>
            
            ' . $optimizations_html . '
            
            <p><strong>Recommended next steps:</strong></p>
            <ul>
                <li>Install <a href="https://wordpress.org/plugins/webp-express/">WebP Express</a> for automatic WebP delivery</li>
                <li>Switch to green hosting (e.g., GreenGeeks, Kualo)</li>
                <li>Avoid bloated frameworks — use compressed images, efficient file formats, and lightweight fonts</li>
            </ul>
            
            <div class="footer">
                <p>
                    This website carbon calculator has been created by 
                    <strong>Wholegrain Digital</strong> to help inspire and educate people to create a zero carbon internet. 
                    It is hosted using renewable energy.
                </p>
                
                <p>
                    GreenAudit WP extends this work — turning awareness into actionable, open-source infrastructure 
                    for a sustainable web.
                </p>
                
                <p>
                    © ' . date('Y') . ' ECO Web Tools — Open Source, Non-Commercial, GPLv3+<br>
                    https://ecowebtools.org
                </p>
            </div>
        </body>
        </html>';

        
$options = $dompdf->getOptions();
$options->setDefaultFont('Helvetica');
$dompdf->setOptions($options);

$dompdf->loadHtml($html);

        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        
        return $dompdf->output();
    }
}